# SPDX-License-Identifier: GPL-2.0

obj-$(CONFIG_SAMPLE_RUST_MINIMAL)		+= rust_minimal.o
obj-$(CONFIG_SAMPLE_RUST_PRINT)			+= rust_print.o
obj-$(CONFIG_SAMPLE_RUST_SPI_DUMMY)		+= spi_dummy.o

subdir-$(CONFIG_SAMPLE_RUST_HOSTPROGS)		+= hostprogs
